--Script
  
CREATE DATABASE TESTDB;
  
CREATE TABLE app_user (
    id INT IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE,
    password VARCHAR(100)
);

CREATE TABLE CUSTOMER (
    ID BIGINT PRIMARY KEY IDENTITY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    CREATED_DATE DATETIME,
    CUSTNO VARCHAR(20) NOT NULL
);
CREATE UNIQUE INDEX CUSTOMER_CUSTNO ON CUSTOMER(CUSTNO);

CREATE TABLE CARD (
    ID BIGINT PRIMARY KEY IDENTITY,
    CUSTNO VARCHAR(20) NOT NULL,
    CARDNO VARCHAR(20) NOT NULL,
    CDAMT DECIMAL(18,2)
);
CREATE UNIQUE INDEX CARD_CUSTNO_CARDNO ON CARD(CUSTNO, CARDNO);

CREATE TABLE cust_card (
    cardno VARCHAR(255) PRIMARY KEY,
    custno VARCHAR(255),
    cdamt NUMERIC(38,2)
);

CREATE TABLE favourite_place (
    id INT IDENTITY PRIMARY KEY,
    user_id INT,
    place_id VARCHAR(100),
    name VARCHAR(200),
    lat FLOAT,
    lng FLOAT,
    FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT uq_user_place UNIQUE (user_id, place_id)
);

  
